id: P8CA3A066
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: zh
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    92d9f8773a5f4b669b5b17c8850561e7:
      title: Advice for Hor Özer
      parent: Advice
    e980b10a71554d74bb494039da731131:
      title: Advice for Palseng
      parent: Advice
    5250358ecb8d4faf980f99fd487720e1:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    ee334a6c9e404c5abe88c774f4031f08:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    c5e4ba0773bf41279b8e09200f953075:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    bca02ec9ebb24c96abf4fb2d94d482e2:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    da1a8bc3cdd0431589efa13331f03ec8:
      title: An Instruction on the Great Perfection
      parent: Advice
    20e4aea04cd644f28f883147e44f0942:
      title: Brief Dzogchen Instruction
      parent: Advice
    e51795cfe92442d6a6519c39cbafc61f:
      title: Direct Instruction
      parent: Advice
    c23952e119964966805807413cdaa70c:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    fded359592c84b768fe819588665cafc:
      title: Vajra Verses on the Natural State
      parent: Advice
    89b17aed1dff444e811ee932f53a1b7a:
      title: Advice for a King
      parent: Advice
    9a38a4e87a474b9598d61d9ef9c516ae:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    97c509f5e89f471493deca7ec3e8e0fe:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    6d906b24f00d4cc382cd1efda2741096:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    6ce0f3acc0b446d6bd3638c91e37d810:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    5d73d7c9f36f49bd90d70aa94b038d54:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    3a68d2bf59394b20b840485283204f7f:
      title: A Liberating Reminder
      parent: Advice
    1cb80830bf204d9cb872408df6986b09:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    3057b6a37c614295a588d9a95d51cc0c:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    1a62baa0d9ad4149abfc3ca1651f62ca:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    de9d9a650bd14a3383f217257c69d392:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    d2f4ca62984246e2a70bd20a9cb0ccc4:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    91da44b45f964f5fb28da190b8f3d5e8:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    b3eefe93447c4712a9908e50dca8a560:
      title: The Essence of Mind
      parent: Advice
    4421981310ec483a8be24eff0adcdae0:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    4140b110342e42b0af87b53841b43063:
      title: The Key Points of Trekchö
      parent: Advice
    c9defb2058bc4a87be83d8c1d23d5e13:
      title: The Nature of Mind
      parent: Advice
    9b66734e28a541f48f9f44f49ececc7b:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    c8ea7cab3a0d4866981bec0833b8d603:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    187ef6cbf1d845faa8a825a92028d460:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    4bd4cc717a564165b83714b28377d35e:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    2c18f704701d490f84ce0ec7c29d000b:
      title: The Five Wisdoms
      parent: Advice
    4f52ebe8638246ebb7db9aa462083d07:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    13ec9d599b774c2c90139be186e8c3a5:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    4b2858375b6c4cf596549cab9d48976d:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    423b8e1a75ba4dfc823a2f6c507981a3:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    9081a3a0603e4211bafed1d456327996:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    6e1d5cba8b084dc087054f8c7981bbe5:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    94205722856e42498048b3f0506c7417:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    0c2d70cddf154040aa28634f06a45c51:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    23f729310e2f4ea1a57e23f62275d505:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    9573d1ae0df7440ba7f5e94bcc02615e:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    99dd6a4633164c3099c89558d7743142:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    25154f0ba6be4f3a8420b17f7e88ff06:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    78c0df60d8104ae7bedb76c2196af400:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    956f26feddc0453a9b90ff511d182361:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    731e3722470f42b6b52e44be6e0477ee:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    be162b2131cf40529fc04b8802741aa0:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    36360cdf1bc74637b16404cd9aa059cb:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    81fd72571ec145b48c36cda4bc71c17a:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    8a3319de109d4174aa9880a450411c17:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    814adaeb57ff4bda80f9b62fd3a16eba:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    31fcd9430f5f4dad8a42381962eb7c36:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    64c0489006324435b77e39d969c1c30e:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    7d00152a63b54f36ad585ddf03f4a3f5:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    706ff74764d7430f82a43d01b79443c0:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    0961efae95954e988432a785c815f2fa:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    18a701e91f6a4ebe865f925ec2f5628e:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    e64247da862d4340b10a82675d43dba4:
      title: The Song of the Vajra
      parent: Songs
    2d4b02a4ea5b4123bc6423972f5bb5be:
      title: A Song in Six Verses
      parent: Songs
    77fc04a38b9e4d99a0672c41db83e401:
      title: Song of Experiential Certainty
      parent: Songs
    5db0e249e0c04fd18d34eb41fbc05d0d:
      title: Spontaneously Written Song of Experience
      parent: Songs
    383627ca37f24c67a6918aebb6eaa660:
      title: In This Pure Awareness
      parent: Songs
    2f97ee4d83704666a8ca40f53743b61c:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    eabfff46b0934bf69640a300c39c5849:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    4bdbf9efbaa84aceb8d8c4ee7d7ea163:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:32.002044'
last_modified_at: '2022-03-01T03:36:32.002047'
